---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set new parameters for reproducible pipeline

```{r}
course <- 'BIOL_228_4001'
```


## Load libraries

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(dplyr)
library(ggplot2)
library(lubridate)
library(scales)
```

## Load helper scripts (functions)

```{r}
source("./scripts/wrangling.R")
source("./scripts/visualizer.R")
```

## Load data

### Set course path

```{r}
course_directory <- paste0("/Volumes/Departments/Extended\ Studies/DEHistData/Analytics_BC/", course, '/input/')
```

### Set data paths

```{r}
dynamics_path <- paste0(course_directory, "dynamics.csv")
grades_path <-paste0(course_directory, "grades.csv")
items_path <- paste0(course_directory, "items.csv")
statics_path <- paste0(course_directory, "statics.csv")
submissions_path <- paste0(course_directory, "submissions.csv")
```

### Read data into memory

```{r}
dynamics <- read.csv(dynamics_path)
grades <- read.csv(grades_path)
items <- read.csv(items_path)
statics <- read.csv(statics_path)
submissions <- read.csv(submissions_path)
```

## Process data

```{r}
## Ensure equal lengths among datasets
# length(unique(dynamics$StudentName))
# length(unique(grades$StudentName))
# length(unique(items$StudentName))
# length(unique(statics$StudentName))
# length(unique(dynamics$StudentName))
```

### Fix time formatting in `dynamics`

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
dynamics <- fix_time_band_24hr(dynamics)
dynamics <- fix_week_level(dynamics_cleaned)
dynamics <- fix_day_of_week(dynamics_cleaned)
```

### Anonymize student identifiers

```{r}
student_roster <- union(dynamics_cleaned$StudentName, grades$StudentName)
student_roster <- union(student_roster, items$StudentName)
student_roster <- union(student_roster, statics$StudentName)

student_count <- length(unique(student_roster))
student_anon_ids <- sample(10000:99999, student_count, replace=FALSE)
student_anon_df <- data.frame(student_roster, student_anon_ids) %>%
  rename(StudentName = student_roster, StudentID_Anon = student_anon_ids)

dynamics <- left_join(dynamics, student_anon_df, by = c("StudentName"))
grades <- left_join(grades, student_anon_df, by = c("StudentName"))
items <- left_join(items, student_anon_df, by = c("StudentName"))
statics <- left_join(statics, student_anon_df, by = c("StudentName"))
```

## Visualization

### Outcomes

#### Final Grade Distribution

```{r}
viz <- viz_FinalGradeDistribution(statics)
viz
```



































