
# Setup

## Set new parameters for reproducible pipeline

```{r}
# REQUIRED PARAMETERS
#course <- '1209_BIOL_227'
#course_directory <- paste0("/Users/bencroft/Google Drive/BIOL/", course, "/")

course <- 'FA19 BIOL 227'
course_directory <- paste0("/Users/bencroft/", course, "/")


# OPTIONAL PARAMETERS:

# Option 1: Combine two course sections
#course1_directory <- 
#course2_directory <- 
#course_combined_directory <- 
#course1_section_number <- 
#course2_section_number <- 
```

## Load libraries

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(dplyr)
library(ggplot2)
library(lubridate)
library(data.table)
library(scales)
library(stringr)
library(ggrepel)
library(ggridges)
library(ggpmisc)
library(kableExtra)
```

## Load helper scripts (functions)

```{r}
source("./scripts/wrangling.R")
source("./scripts/visualizer.R")
source("./scripts/section_combiner.R")
```

## Load data

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
course_activity <- read.csv(paste0(course_directory, "course_activity.csv"))
course_item_activity <- read.csv(paste0(course_directory, "course_item_activity.csv"))
course_summary <- read.csv(paste0(course_directory, "course_summary.csv"))
forum_submissions <- read.csv(paste0(course_directory, "forum_submissions.csv"))
grade_center <- read.csv(paste0(course_directory, "grade_center.csv"))
main <- read.csv(paste0(course_directory, "a4l_main.csv"))
student_course_summary <- read.csv(paste0(course_directory, "student_course_summary.csv"))
sis <- read.csv(paste0(course_directory, "sis.csv"))
prereq <- readr::read_csv(paste0(course_directory, "prerequisites.csv"))
```


```{r}
sis
```






```{r}
sis %>%
  filter(Term == "Fall 2020") %>%
  filter(InstructionMode == "Online") %>%
  filter(Subject == "BIOL") %>%
  filter(CourseNumber == 227) %>%
  filter(Section %in% c("4001", "4002")) %>%
  filter(VersionKey == 1) %>%
  select(VersionDescription, TermSourceKey, Term, InstructionMode, Subject, CourseNumber, ClassNumberUniqueDescription, Section, Instructor,
         StudentID, AcademicPlan, StudentAge, BSUIPEDSEthnicity, Gender, FirstTermAtInstitution, CumulativeGPA, FirstGen, AcademicLevel,
         HasTransferCumGPA, FullTimePartTimeDescription, 
         EnrollStatus, EnrolledClassCount, DropCount, WithdrawCount, RegistrationAddDate, RegistrationDropDate,
         CreditsAttempted, CreditsEarned, EarnCreditIndicator, SuccessIndicator, HasClassGrade, ClassGrade, GradeLetter, GradePoints, GradeGroup) %>%
  distinct() %>%
  group_by(StudentID) %>%
  filter(C)
  
  
  #group_by(StudentID) %>%
  #summarise(C = n()) %>%
  #arrange(desc(C))  
  
  filter(StudentID == 114050872)
```


```{r}
sis %>%
  group_by(StudentID) %>%
  summarise(C = n()) %>%
  arrange(desc(C))
```

```{r}
sis %>%
  filter(Term == "Fall 2020") %>%
  filter(InstructionMode == "Online") %>%
  filter(Subject == "BIOL") %>%
  filter(CourseNumber == 227) %>%
  filter(Section %in% c("4001", "4002")) %>%
  filter(VersionKey == 1) %>%
  select(VersionDescription, TermSourceKey, Term, InstructionMode, Subject, CourseNumber, ClassNumberUniqueDescription, Section, Instructor,
         StudentID, AcademicPlan, StudentAge, BSUIPEDSEthnicity, Gender, FirstTermAtInstitution, CumulativeGPA, FirstGen, AcademicLevel,
         HasTransferCumGPA, FullTimePartTimeDescription, 
         EnrollStatus, EnrolledClassCount, DropCount, WithdrawCount, RegistrationAddDate, RegistrationDropDate, UniqueDescription,
         CreditsAttempted, CreditsEarned, EarnCreditIndicator, SuccessIndicator, HasClassGrade, ClassGrade, GradeLetter, GradePoints, GradeGroup) %>%
  distinct() %>%
  filter(StudentID == 114063978)
```








# Viz

## Outcomes

### Outcomes by Section

```{r}
student_course_summary
```



#### Bar plot

```{r, fig.width = 13, fig.height = 8}
tmp <- student_course_summary %>%
  filter(IsEnrolledSIS == 1) %>%
  filter(NormalizedScore > 0) %>%
  filter(!SISGradeLetter %in% c("W", "CW", "I")) %>%
  filter(CourseRole == "Student") %>%
  filter(Course != "Fa20 - BIOL 227 - Honors LECTURE Human Anatomy & Physiology I") %>%
  left_join(main, by = c("Course" = "COURSE_NAME")) %>%
  mutate(Section = as.character(Section)) %>%
  select(Term, CourseNumber, Section, UniqueDescription, InstructionMethod.x, Instructor, Student, NormalizedScore, SISClassLevel) %>%
  mutate(InstructorLast = word(Instructor, 1)) %>%
  mutate(CourseNumberSectionInstructor = paste0(CourseNumber, " ", Section, " ", InstructorLast)) %>%
  mutate(CourseNumberSectionInstructor = gsub(",", "", CourseNumberSectionInstructor)) %>%
  arrange(Student)

tmp$SISClassLevel <- factor(tmp$SISClassLevel, levels = c("Freshman", "Sophomore", "Junior", "Senior", "Post-Bacc Undergraduate", "Graduate", "No SIS Match"))
  
tmp %>%
  group_by(Student) %>%
  summarise(C = n()) %>%
  arrange(desc(C))

tmp

```

#### Ridges

```{r, fig.width = 13, fig.height = 8}
tmp <- student_course_summary %>%
  filter(IsEnrolledSIS == 1) %>%
  filter(NormalizedScore > 0) %>%
  filter(!SISGradeLetter %in% c("W", "CW", "I")) %>%
  filter(CourseRole == "Student") %>%
  filter(Course != "Fa20 - BIOL 227 - Honors LECTURE Human Anatomy & Physiology I") %>%
  left_join(main, by = c("Course" = "COURSE_NAME")) %>%
  mutate(Section = as.character(Section)) %>%
  select(Term, CourseNumber, Section, UniqueDescription, InstructionMethod.x, Instructor, Student, NormalizedScore, SISClassLevel) %>%
  mutate(InstructorLast = word(Instructor, 1)) %>%
  mutate(CourseNumberSectionInstructor = paste0(CourseNumber, " ", Section, " ", InstructorLast)) %>%
  mutate(CourseNumberSectionInstructor = gsub(",", "", CourseNumberSectionInstructor)) %>%
  arrange(Student)

tmp$SISClassLevel <- factor(tmp$SISClassLevel, levels = c("Freshman", "Sophomore", "Junior", "Senior", "Post-Bacc Undergraduate", "Graduate", "No SIS Match"))
  
tmp %>%
  group_by(Student) %>%
  summarise(C = n()) %>%
  arrange(desc(C))

tmp


ggplot(tmp, aes(x = NormalizedScore, y = Section, fill = Section, color = Section)) +
    geom_density_ridges(scale = 4, alpha = 0.5) +
    
    scale_x_continuous(expand = c(0, 0), limits = c(0, 110)) +   # for both axes to remove unneeded padding
    #scale_y_discrete(expand = c(0, 0)) +     # will generally have to set the `expand` option
    coord_cartesian(clip = "off") + # to avoid clipping of the very top of the top ridgeline
    theme_ridges() +
    scale_fill_manual(values = c("#003f5c", "#bc5090","#58508d","#ff6361", "#ffa600")) +
    scale_color_manual(values = c("#003f5c", "#bc5090","#58508d",  "#ff6361", "#ffa600")) +
    scale_y_discrete(limits = rev(levels(as.factor(tmp$Section)))) +
    theme(legend.position = "bottom",
          legend.box = "vertical",
          legend.title = element_blank(),
          axis.text.y = element_text(size = 11),
          axis.text.x = element_text(size = 11),
          axis.title.y = element_blank(),
          axis.title.x = element_text(size = 16, color = "gray50", vjust = 0)) +
    guides(fill=guide_legend(nrow=2, byrow = TRUE)) + 
    scale_x_continuous(limits = c(50, 100))
```


### Outcomes by Major

```{r, fig.height = 8, fig.width = 10}
tmp1 <- student_course_summary %>%
  filter(IsEnrolledSIS == 1) %>%
  filter(NormalizedScore > 0) %>%
  filter(!SISGradeLetter %in% c("W", "CW", "I")) %>%
  filter(CourseRole == "Student") %>%
  filter(Course != "Fa20 - BIOL 227 - Honors LECTURE Human Anatomy & Physiology I") %>%
  select(SISMajor, NormalizedScore) %>%
  group_by(SISMajor) %>%
  summarise(Count = n()) %>%
  arrange(desc(Count)) %>%
  filter(Count >= 5)

tmp2 <- student_course_summary %>%
  filter(IsEnrolledSIS == 1) %>%
  filter(NormalizedScore > 0) %>%
  filter(!SISGradeLetter %in% c("W", "CW", "I")) %>%
  filter(CourseRole == "Student") %>%
  filter(Course != "Fa20 - BIOL 227 - Honors LECTURE Human Anatomy & Physiology I") %>%
  left_join(main, by = c("Course" = "COURSE_NAME")) %>%
  mutate(Section = as.character(Section)) %>%
  select(Term, CourseNumber, Section, UniqueDescription, InstructionMethod.x, Instructor, Student, NormalizedScore, SISMajor) %>%
  mutate(InstructorLast = word(Instructor, 1)) %>%
  mutate(CourseNumberSectionInstructor = paste0(CourseNumber, " ", Section, " ", InstructorLast)) %>%
  mutate(CourseNumberSectionInstructor = gsub(",", "", CourseNumberSectionInstructor)) %>%
  select(SISMajor, NormalizedScore) %>%
  filter(SISMajor %in% tmp1$SISMajor)
  # group_by(SISMajor) %>%
  # summarise(Count = n(), 
  #           GradePercent_Mean = mean(NormalizedScore), 
  #           GradePercent_Median = median(NormalizedScore), 
  #           GradePercent_SD = sd(NormalizedScore)) %>%
  # arrange(desc(Count)) %>%
  # filter(Count >= 5)

# Create plot
tmp2 %>%
  ggplot(aes(y = NormalizedScore, x = SISMajor)) +
  geom_boxplot(aes(fill = SISMajor)) +
  geom_jitter(width = 0.10) +
  my_theme() +
  labs(
    #title = "Course Outcomes by Student Credit Load", 
       y = "Course Grade (Percent)", 
       x = "", 
       color = "Credit Load",
       #subtitle = "Summer 2020 BIOL 228 | Section 4001 and 4002",
       caption = "Note: This dataset excludes students who withdrew or had an incomplete term \n Plans include 5 or more (duplicated) students.") +
  #scale_fill_manual(values = c("#009DD9", "#999999")) +
  theme(legend.position = "") +
  scale_y_continuous(limits = c(0, 100)) +
  #facet_wrap(~CourseNumberSectionInstructor) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
  theme(axis.text.x = element_blank()) +
  theme(legend.position = "left")
```



### Outcomes by Class Level

```{r, fig.width = 13, fig.height = 8}
tmp <- student_course_summary %>%
  filter(IsEnrolledSIS == 1) %>%
  filter(NormalizedScore > 0) %>%
  filter(!SISGradeLetter %in% c("W", "CW", "I")) %>%
  filter(CourseRole == "Student") %>%
  filter(Course != "Fa20 - BIOL 227 - Honors LECTURE Human Anatomy & Physiology I") %>%
  left_join(main, by = c("Course" = "COURSE_NAME")) %>%
  mutate(Section = as.character(Section)) %>%
  select(Term, CourseNumber, Section, UniqueDescription, InstructionMethod.x, Instructor, Student, NormalizedScore, SISClassLevel) %>%
  mutate(InstructorLast = word(Instructor, 1)) %>%
  mutate(CourseNumberSectionInstructor = paste0(CourseNumber, " ", Section, " ", InstructorLast)) %>%
  mutate(CourseNumberSectionInstructor = gsub(",", "", CourseNumberSectionInstructor)) %>%
  arrange(Student)

tmp$SISClassLevel <- factor(tmp$SISClassLevel, levels = c("Freshman", "Sophomore", "Junior", "Senior", "Post-Bacc Undergraduate", "Graduate", "No SIS Match"))
  
tmp %>%
  group_by(Student) %>%
  summarise(C = n()) %>%
  arrange(desc(C))

tmp

# Create plot
tmp %>%
  ggplot(aes(y = NormalizedScore, x = SISClassLevel)) +
  geom_boxplot(aes(fill = SISClassLevel)) +
  geom_jitter(width = 0.10) +
  my_theme() +
  labs(
    #title = "Course Outcomes by Student Credit Load", 
       y = "Course Grade (Percent)", 
       x = "", 
       color = "Credit Load",
       #subtitle = "Summer 2020 BIOL 228 | Section 4001 and 4002",
       caption = "Note: This dataset excludes students who withdrew or had an incomplete term") +
  #scale_fill_manual(values = c("#009DD9", "#999999")) +
  theme(legend.position = "") +
  scale_y_continuous(limits = c(0, 100)) +
  facet_wrap(~CourseNumberSectionInstructor) +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) +
  theme(axis.text.x = element_blank()) +
  theme(legend.position = "top")
```


## Items




